[package]
name = "simple_web_server"
version = "0.1.0"
authors = ["Shinya TAKEBAYASHI <takebayashi.shinya@nttcom.co.jp>"]

[dependencies]
iron = "0.5.1"
mime = "0.2.3"
router = "0.5.1"
urlencoded = "0.5.0"
